Component generator
futuredapp/kmp-futured-template pull request #65
Opened 2024-04-16 20:21 UTC by RudolfHladik

Add KSP Processor for generating components from `ScreenInterface`

2024-06-29 10:22 UTC, matejsemancik requested changes
Needs some ironing out, otherwhise, this is a nice idea, wonder what other usecases can we cover with this.

2024-06-29 10:22 UTC, matejsemancik commented on shared/util/component-processor/build.gradle.kts
> +}
Does the processor need multiplatform plugin? I think you should be able to get it working using just jvm plugin?

2024-06-29 10:22 UTC, matejsemancik commented on shared/util/component-processor/src/jvmMain/kotlin/com/rudolfhladik/componentprocessor/ComponentProcessor.kt
> +package com.rudolfhladik.componentprocessor
Can you update package name?

2024-06-29 10:22 UTC, matejsemancik commented on shared/util/component-processor/src/jvmMain/kotlin/com/rudolfhladik/componentprocessor/ComponentProcessor.kt
> +    private val logger: KSPLogger,
Logger is unused, wanna keep it in? (I'm literally doing Danger's work here, which reminds me there should be `ktlint` and `danger` plugins added in `component-processor` and `component-annotations` Gradle projects)

2024-06-29 10:22 UTC, matejsemancik commented on shared/util/component-annotation/src/commonMain/kotlin/com/rudolfhladik/annotation/ComponentAnnotation.kt
> +annotation class NavigationComponent()
This annotation class is unused, pls remove

2024-06-29 10:22 UTC, matejsemancik commented on shared/util/component-processor/src/jvmMain/kotlin/com/rudolfhladik/componentprocessor/content/ComponentPoetGenerator.kt
> +class ComponentPoetGenerator { // TODO cant access classes from other modules
I guess this is WIP version of generator using Kotlin Poet?

It appears to be unused, pls
- remove this class (we can add it later when finished)
- remove kotlin poet dependency

2025-02-07 12:01 UTC, closed without merging

2025-02-07 12:01 UTC, RudolfHladik commented
No longer needed as in v3 we use Retained components